---
editor_options: 
  markdown: 
    wrap: 72
---

# Endovascular

## Vascular Access

**Authors:** Sammy Siada, DO, RPVI; Rafael Demarchi Malgor, MD, MBA,
FACS

```{r echo=FALSE}

library(embedr)

embed_audio("https://traffic.libsyn.com/audiblebleeding/Vascular_Access_1.mp3")

```

Endovascular procedures are the cornerstone of any modern vascular
surgery practice. Because most endovascular procedures are performed
percutaneously using arterial or venous access, it is critical that
vascular surgeons are facile with various techniques and devices used
for endovascular access. Today we'll be discussing the various access
sites, techniques for access, closure devices, and complications.

**What factors play a role when choosing a site for access?**

The factors to think about when thinking about which vessel to access
are:

-   The appropriateness of the access site the procedure performed

-   Ability to obtain hemostasis at the conclusion of the procedure

-   Ability to convert to open if necessary

-   Effects of access on the tissues supplied by the accessed vessel and
    distal limb perfusion

**What makes a vessel appropriate for access?**

One of the most important factors when planning your access is the size
of the vessel. The vessel needs to be able to accommodate the catheters
and devices that will be used to perform the procedure. For instance, a
brachial artery with less than 4mm diameter should not be accessed by a
large bore sheaths, such as a 12Fr sheath.

The vessel also needs to be a in a location that can allow access to the
target vessel of interest. Additionally, the vessel needs to have an
area that is relatively healthy to access the vessel safely and minimize
complications. Heavily calcified vessels especially those with anterior
wall calcification might not be appropriate for access.

**What about the ability obtaining hemostasis at the end of the
procedure?**

The ability to obtain hemostasis is critical to be able to perform
endovascular procedures safely which is one reason why the common
femoral artery is the most commonly accessed vessel.

Hemostasis is most commonly achieved through manual compression by
compressing the artery against the femoral head. The brachial artery can
also be compressed against the humerus, but because it's a more mobile
vessel, compression is less effective and can lead to hematoma or
pseudoaneurysm formation which may necessitate an operation to prevent
compression of the median nerve

Patients who will need to be uninterruptedly anticoagulated peri and
postoperatively pose a challenge to hemostasis. The use of closure
devices is very important in these situations to prevent access
bleeding.

A variety of closure devices can also be used to assist in hemostasis,
each with their own inherent advantages and disadvantages. In general,
closure devices are contraindicated in small diameter and heavily
calcified vessels.

**In any minimally invasive procedure, there is always a chance that you
may need to convert to open. How does converting to open play a role in
vascular access?**

Conversion to open is uncommon with vessel access accounting for \<5% of
the cases. Sometimes a large sheath is accidentally pulled out and a
cutdown becomes necessary to repair the artery. Closure devices aren't
100% effective in hemostasis and may also require a cutdown for
definitive control if they fail, especially when obtaining large bore
access.

This makes choosing the right vessel critical. For example, if a large
sheath is accidentally pulled out of the CFA during an EVAR, the repair
can be done through a straightforward groin cutdown. In contrast, the
subclavian artery is rarely accessed percutaneously because converting
to open would require a more challenging peri-clavicular incision or
even a thoracotomy for repair.

**Large diameter sheaths are often used, particularly in aortic
procedures. These sheaths can be occlusive which can result in
downstream tissue ischemia. What considerations should be taken when
thinking about downstream tissue ischemia?**

When performing diagnostic procedures using small diameter sheaths and
catheters, anticoagulation may or may not be necessary depending on how
diseased the access vessel is.

However, when using large devices (e.g. in EVARs), the sheaths can be
partially or completely occlusive which mandates full anticoagulation to
prevent thrombosis. The other thing to consider is the length of time
that the sheath remains in the vessel as the leg can only tolerate
ischemia for 4-6 hours. This is usually pertinent when performing
complex endovascular aortic procedures.

To minimize downstream tissue ischemia, a large bore sheath should be
pulled back to decrease the length of vessel obstruction by its shaft in
order to unblock proximal vessel collateral branch vessels. For
instance, when performing an aortic procedure through a femoral access
attempt to pull the sheath back into the external iliac artery to
increase distal limb perfusion through the internal to femoral artery
collateral branch vessels.

The long story short is to be liberal with anticoagulation when there is
reduced flow in the vessel such as the iliofemoral system during EVAR or
tibial access

**Do the principles that we've described also apply to veins?**

The same principles apply but there are some notable differences between
arterial and venous access.

Veins are a low-pressure system, so hemostasis is easier to achieve and
hemorrhagic complications are much less common. However, this poses a
challenge during access as there is less radial force keeping the vein
open making the vein more susceptible to compression by the ultrasound
probe and the needle.

If a large bore sheath is necessary to perform a venous procedure, a
suture-mediated closure device can be utilized to achieve hemostasis
especially in patients that will be kept fully anticoagulated

Additionally, a syringe may be needed to confirm access and can also
prevent air embolism

**Let's talk about accessing the common femoral artery. Why is the CFA
the most common vessel used for access?**

It is large caliber and can accommodate large sheaths up to 26-28 Fr. It
also allows for a wide set of procedures and is ergonomically easy to
work with given its location. It is relatively easy to hold manual
pressure and if a conversion to open is needed, a femoral cutdown is
relatively straightforward.

**Where in the common femoral artery is the best spot to access?**

The ideal puncture site is in the CFA in the medial third of the femoral
head in between the inguinal ligament and the femoral bifurcation in the
middle of the femoral head.

Accessing the vessel above the inguinal ligament makes compressing the
artery very difficult which can lead to life-threatening retroperitoneal
bleed.

A puncture that is too distal and into the SFA increase the risk of
thrombosis or dissection causing acute limb ischemia as well as AV
fistula formation between the superficial femoral and profunda femoris
artery.

**What are the different ways to obtain CFA access?**

There are three different ways to access the CFA: manual palpation,
fluoroscopic guided, and ultrasound guided.

With manual palpation, a finger is placed above and below the desired
access point directly on the pulse and the needle is inserted in between
the two fingers.

Fluoroscopic guidance uses bony landmarks relative to the position of
the needle.

The standard of care in the modern era for obtaining CFA access is to
use ultrasound guidance. Ultrasound allows visualization of the vessel
and surrounding structures. PAD within the vessel can readily be
identified with ultrasound, allowing safe access in a relatively
disease-free part of the artery. Ultrasound also clearly shows the
femoral bifurcation. Using ultrasound allows for subtle corrections in
the angle of the needle and how it interacts with the surrounding
tissues. It is rapid, real-time, inexpensive, and safe.

**What anatomic considerations should be taken when accessing the CFA?**

The CFA is the continuation of the external iliac artery as it courses
under the inguinal ligament. It is about 5-8 cm in length and then
bifurcates in to the superficial femoral and profunda femoris arteries

The inguinal ligament is a good external landmark to estimate where the
CFA is. It is critical to emphasize that the inguinal ligament does not
correspond to the groin crease and this is especially true in obese
patients. An imaginary line is drawn from the ASIS to the pubic
tubercle. The artery generally runs a third of the way from the pubic
tubercle to the ASIS. A metallic instrument can be placed in this area
to mark it externally and a fluoroscopic image can be obtained to
identify the relation of the instrument to the medial third of the
femoral head. This imaginary line also marks the superior-most extent of
the access

The CFA is most often accessed in a retrograde fashion in between the
inguinal ligament and femoral bifurcation. This allows for a multitude
of potential diagnostic and therapeutic procedures in most parts of the
body.

**Can the CFA be accessed antegrade?**

Yes. Sometimes antegrade CFA access is used when performing an
intervention distal on the ipsilateral leg. The advantage of antegrade
access is better pushability and torquability of wires, catheters, and
sheaths when performing complex peripheral intervention where no other
proximal procedures are needed.

Antegrade access is more challenging than retrograde access, however.
This is particularly true in patients with a very short CFA, short
distance between the inguinal ligament and the femoral bifurcation
because the needle requires a steeper angle of entry to allow for
cannulation well above the femoral bifurcation.

Obtaining antegrade access is especially difficult in obese patients and
will usually require an assistant to retract the pannus to allow proper
needle placement. I would say antegrade access is relatively
contra-indicated in morbidly obese patients with large pannus.
Ultrasound guidance remains key here as well.

**What are some other commonly accessed arteries for endovascular
procedures?**

The tibial vessels can be accessed percutaneously for retrograde
recanalization for severe LE PAD. It is usually performed using
micropuncture kits which we will discuss a little later. It is usually
done with ultrasound guidance and uses small sheaths and wires. The PT
and AT are more commonly used because they are easier to access.

The radial artery is commonly used in coronary interventions and is
increasingly being used by vascular surgeons. It is easily palpable over
the distal radius and can be cannulated with ease. Hemostasis is
straightforward using compression. In the rare setting of radial
occlusion, the hand rarely becomes ischemic because most people are
ulnar dominant. It can accommodate sheaths up to 6 French.

-   The best way to reduce vasospasm and injury to the radial artery is
    utilizing a radial artery cocktail - calcium channel blocker,
    vasodilator, and anticoagulation.[@mason2018; @cauley2019]

The brachial artery can be accessed percutaneously over the olecranon
process with the arm supinated.[@alvarez-tostado2009] Ultrasound
guidance allows for visualization of the brachial bifurcation. It can
accommodate 6-7 Fr sheaths. Hemostasis is critically important as
bleeding can result in a hematoma that results in median nerve
compression, which is a surgical emergency. Cut down after brachial
access has been shown to reduce complications.[@kret2016]

**Let's not forget about venous access. What are some of the most
commonly accessed veins?**

The CFV is commonly accessed for procedures involving the IVC and iliac
vessels and their branches for conditions such as May-Thurner, pelvic
congestion syndrome, and IVC filter placement. Treatment of PE can also
be performed through the CFV. The CFV can easily be compressed over the
femoral head and is located medial to the CFA. Ultrasound guidance
should be used to prevent arterial injury and backwalling.

The internal jugular vein can be accessed using US guidance (to prevent
carotid injury; IJ is lateral to the carotid). IJ access is used most
commonly for central venous catheters as well as IVC placement and
filter retrieval. It is also an excellent access to treat pulmonary
embolism via thrombolysis or thrombectomy. The IJ can be utilized to
perform ovarian and internal iliac vein embolization. IJ is also the
preferred access to perform TIPS, which is often of less interest to
vascular surgeon.

The popliteal vein can be accessed with the patient in the prone
position or the distal femoral vein in the supine position to diagnose
and treat DVTs of the extremity veins. Ultrasound is also helpful to
avoid arterial access and especially if the vein is thrombosed

Arm veins (cephalic/basilic) can be also readily accessed for vein
mapping or fistula interventions.

**Let's move on to access technique. Historically, there are two types
of puncture needles: single-wall and double-wall. Can you talk about the
differences?**

Double wall needles were commonly used back in the day for femoral
access. They have an outer hollow blunt-tipped needle and an inner sharp
stylet. The needle was inserted through and through the artery and the
stylet removed and the blunt hollow needle pulled back until blood is
returned. These aren't favored anymore because they cause unnecessary
backwalling of the artery. Double wall access kits are used in treating
endoleaks from both a transcaval and translumbar routes to allow access
into the aneurysm sack and needle removal to avoid puncturing the
endograft.

Single wall needles are typically the choice for diagnostic procedures.
18-gauge needles accommodate an 0.035 in wire and 21 gauge accommodates
a 0.018 in wire.

**Can you describe the micropuncture technique for percutaneous
access?**

Micropuncture technique is the most commonly used method for
percutaneous access nowadays. The advantage of the micropuncture
technique is the use of a small needle which can be removed and
repositioned with a negligible risk of bleeding and minimal amount of
manual compression needed.

Ultrasound is used to cannulate the artery with a 21-gauge needle. It is
best to visualize the needle entering the artery and to be intraluminal
without being against the wall Blood return is then seen and a floppy
tip micropuncture (0.018) wire is inserted under fluoroscopic guidance
to make sure the wire passes into the vessel easily. A 4 Fr introducer
sheath is placed over the wire gently to avoid kinking the wire. The
inner cannula of the sheath is removed, and a 0.035 guidewire is placed
under fluoroscopic guidance. It is important to remember that there are
two types of introducer sheath depending on amount of subcutaneous scar
tissue containing either a soft or a stiffened cannula. The 4 Fr is
removed over the wire while holding manual pressure and desired sheath
(usually 5 or 6 Fr) is placed for definitive access. The side port is
then aspirated for arterial blood and flushed with heparinized saline.

## Complications {#access-comp}

**With any invasive procedure, there are risks of complications. What
are some of the complications of percutaneous vascular access?**

Hematomas are the most common complication and have an incidence of
about 3%. Most of these hematomas are clinically insignificant but
retroperitoneal hemorrhage from a high puncture above the inguinal
ligament can be life-threatening. These may require conversion to open
and direct repair of the vessel or covered stent placement (especially
if the puncture is above the inguinal ligament). Proximal balloon
occlusion can be helpful to control hemorrhage while the vessel is being
repaired.

Groin hematomas are not uncommon and are usually self-limiting. An
expanding hematoma that is seen early can be treated with simple manual
pressure at the bedside. If the hematoma is large and compressing
surrounding structures or threatening skin integrity or if the patient
is hemodynamically unstable, then surgical evacuation may be necessary

Pseudoaneurysms are an uncommon complication with an incidence of about
0.6%. Most pseudoaneurysms are treated with ultrasound-guided
compression or thrombin injection. Thrombin injection requires a narrow
neck into the pseudoaneurysm. If the pseudoaneurysm is \>2cm, compresses
surrounding structures, threatens skin integrity, or has failed thrombin
injection, then surgical repair is required.[@morgan2003; @stone2014]
For a representative image, see \@ref(psa)

Thrombosis of the CFA is a known complication but fortunately is rare
with an incidence of 0.2%. This can result from manual compression of
the CFA that has severe atherosclerotic disease or prior groin
reconstruction. This generally requires a cutdown, endarterectomy,
thrombectomy, and patch angioplasty.

Lastly, AV fistula can form and are usually between the femoral artery
and vein with an incidence of 0.5-0.9%). These usually occur from a low
puncture of the CFA bifurcation or profunda. They are usually
asymptomatic and detected on exam (palpable thrill) and confirmed with
duplex imaging. If the fistula is small, it generally can be observed
with close duplex surveillance. If it enlarges or becomes symptomatic,
then repair is indicated. Covered stent grafts can be placed with
minimal morbidity, making this optimal for high risk patients. Open
surgery also is highly successful. Deciding between non-operative,
endovascular, or open treatment is up for debate and is up to the
clinical judgement of the surgeon.

## Radiation Safety

**Authors:** Adam Johnson, MD, MPH

### Important Terms

**Absorbed Dose** - energy deposited by ionizing radiation in a medium
per unit mass. Dosage measured and communicated most commonly in Gray
(Gy) equal to 100 rad.[@reed2019]

**Effective Dose** - energy deposited by ionizing radiation in a medium,
taking into account the sensitivity of the specific tissue, time and
duration of exposure. These factors compose a weighting factor (W) and
thus this is calculated by multiplying absorbed dose (Gy) by the
weighting factor (W). Dosage measured and communicated most commonly in
Sievert (Sv) equal to 100 rem.[@reed2019]

**Reference Air Karma (RAK)** - Radiation output at a specific reference
point along a fluoroscopic axis.[@kirkwood2013]

-   Located 15cm along the beam axis toward the focal spot from the
    isocenter.

-   Best approximation of cumulative patient dose or peak skin dose
    (PSD).[@kwon2011]

-   Includes dose from fluorsocopy and fluorography acquisitions,
    however does not account for gantry angulation of changes in height.

**Substantial Radiation Dose Level (SRDL)** - defined as 5Gy exposure,
which translates to a skin dose of 3Gy and should trigger specific
patient follow up.[@baiter2011; @hirshfeld2005; @kirkwood2015;
@stecker2009]

### Radiation effects

The effects can impact both patients and clinicians. Patients often
receive a higher dose during a single procedure, where as clinician
doses, even with proper shielding, accumulate over multiple procedures
throughout their careers. The effects of radiation are defined as either
deterministic or stochastic.

|  Dose   | Effect                                                                                             |
|:-------:|----------------------------------------------------------------------------------------------------|
|  0-2Gy  | No observable effects                                                                              |
|  2-5Gy  | Transient skin erythema and dermatitis, full recovery 6w-1yr[@guesnier-dopagne2019; @kirkwood2014] |
| 5-10Gy  | Erythema and epilation (hair loss), prolonged erythema up to 1y                                    |
| 10-15Gy | Permanent epilation, atrophy or induration up to 1y                                                |
| \>15Gy  | Dermal Necrosis                                                                                    |

: Skin related deterministic effects that can be seen after a single
exposure over a certain threshold [@balter2010; @hirshfeld2005;
@kirkwood2014; @stecker2009; @wagner1999]

The ocular lens is the most radio-sensitive tissue and cataracts is an
unfortunately common deterministic effect.[@machan2018; @brown2011]
Annual limits for ocular exposure include 20mSv per year and total
threshold of 0.5Gy.

Stochastic effects can occur after exposure of any dose, but are seen
more frequently in populations with higher radiation exposure. These are
based on population studies and exact dose dependent relationships have
not been established. These include:

-   Brain cancer[@rajaraman2016; @kirkwood2018]

-   Breast and thyroid cancer[@johnson2001; @einstein2012]

### Risk factors

Certain patient, procedure and clinician factors put patients at
increased risk for radiation exposure.[@killewich2011; @mitchell2011]
These should be considered when planing and executing endovascular
procedures to ensure that dosages are as low as reasonably achievable
(ALARA)

-   Patient Factors

    -   Obesity

-   Procedure Factors

    -   Case complexity

    -   Need for magnification

    -   Case orientation and angulation

-   Clinician Factors

    -   Use of multiple subtraction runs

### Reduction strategies

The main source of radiation to the clinicians is scatter from the
patient. There are a number of techniques that can be used to reduce
exposure of clinicians to this radiation.[@heidbuchel2014;
@kirkwood2013]

-   Reduce the time of exposure, keeping a close eye on fluoroscopy time
    and dosages as a procedure progresses.

-   Position the source as far away from the operator as possible to
    still achieve optimal imaging. Radiation dose changes according to
    the inverse square of distance. Therefore twice the distance results
    in one quarter the dose.

    -   For example, left anterior oblique (LAO) will bring the source
        to the patient's right side, causing higher doses to clinicians
        on that side of the patient.[@kirkwood2013; @sailer2019]

-   Appropriate shielding

    -   The location with the highest exposure to scatter is below the
        table.[@gonzales2014; @miller2010] Therefore, leaded skirt and
        extended lower body shields reduce radiation to the operator's
        legs.[@kirkwood2015]

    -   Of note: leaded caps DO NOT reduce radiation exposure to the
        brain because the majority of radiation is received as scatter
        from the patient up through the face and neck.[@kirkwood2018]

    -   Lead shielding should be regularly inspected and discarded if
        damaged. Particularly if defect is \>15mm2 on a critical organ
        area, \>670mm2 along a seem/overlapping area, \>11mm2 on a
        thyroid shield.[@officeofhealthcareinspections2014; @university]

-   Collimation can be helpful to reduce patient and operator dose,
    scatter and improve image quality.[@haqqani2012]

-   Use last image hold to allow for procedural planning

### Pregnancy considerations

Pregnancy of both patients and clinicians need to be considered in
relation to radiation exposure and safety.[@chandra2013; @mitchell2011;
@shaw2011] This is a highly tested subject on vascular surgery
examinations. Some important take aways include:

-   CDC has released guidance for potential prenatal effects on
    radiation exposure[@cdc2011] The majority of effects on fetuses is
    extrapolated from studies of the fall out from Hiroshima, Nagasaki
    and Chernobyl.

    -   \<0.05Gy represents no measurable risk to embryo or fetus at any
        gestational age.

    -   0.05-0.5Gy can be dangerous in the first trimester, but has not
        been associated with defects later in pregnancy.[@shaw2011]

    -   \>0.5Gy can be dangerous at any point during pregnancy.

-   Dose limit recommendations during the 9 months of pregnancy is
    500mrem or 50mrem per month.[@dauer2015; @chandra2013]

Strategies to reduce exposure include:

-   Avoid direct fluoroscopy to the fetus, high-gantry angulation, and
    femoral access

    -   Use collimation to ensure fetus is excluded from imaging field.

-   Use adjuncts of intravascular ultrasound and lead shielding when
    able.

-   Reduce machine kilo-voltage and milliampere/second.

-   Remove the anti-scatter grid to reduce dosage to patient.[@tomà2019]

-   Limit fluoro time.

-   Some recommendations state that operators who intend to get pregnant
    should start wearing maternity aprons (lead equivalent to 1mm) even
    prior to knowing they are pregnant.[@shaw2011]

    -   Original studies demonstrated reduction in fetal exposure by
        80%.[@witrak1984]

    -   However, a recent multi-institutional review showed that fetal
        exposure is minimal even in regular lead, therefore the
        additional weight of maternal lead may be
        unnecessary.[@chandra2013]

### Regulation

Joint Commission Oversight - sentinel radiation reporting is aimed to
promote awareness of preventable events perform root cause analyses to
understand the reasons for events.[@thejointcommission2019] It is
important to escalate events early, as effects may not occur until much
later.[@arbique] Sentinel events include:

1.  Cumulative dose of 15 Gy for a single field over 6mo - 1yr.

2.  Delivery of radiotherapy to the wrong body region.

3.  Actual dose more than 25% above planned radiotherapy
    dose.[@jones2011]

Institutional Oversight - many institutions develop their own guidelines
for employee exposure and mitigation strategies. Some common policies
regarding dose limits include:

-   Monthly limit for dosimeter reading of 100mrem per month.

-   Recommendations for annual occupational dose is \<20mSv per year
    averaged over 5y and no more than 50mSv in any one year.
    Occupational dose \<100mSv per year is not thought to increase
    cancer risk

    -   Recent reduction of occupational dose limit to 50mSv is due to
        increasing data connecting cataracts to radiation
        exposure.[@hamada2017]

## Contrast Reduction

The most common complications related to iodinated contrast during
endovascular procedures are hypersensitivies and acute kidney injury.
There are a number of mitigation strategies to limit the effect of
contrast on patients undergoing endovascular procedures.

In general patients with food allergies do have an increased incidence
of contrast media allergies, however no specific common allergen has
been identified. A new seafood allergy should not postpone or require
pre-medication if a patient has previously tolerated IV
contrast.[@schabelman2010]

### CO2 Angiography

CO2 angiography is often utilized in place of iodinated contrast during
fluoroscopy. A bolus of CO2 is injected, which then absorbs less
ionizing radiation than surrounding tissue and provides a map of the
arterial tree. CO2 can be used in a wide range of endovascular
procedures, even a ruptured AAA.\@knipp2010 However, there are specific
limitations and complications that should be understood.

#### Limitations

-   Contraindicated in imaging above the diaphragm.[@caridi1997;
    @sharafuddin2017]

-   Susceptible to bolus fragmentation and often requires stacking to
    fully visualize the target arterial bed.[@caridi1997;
    @sharafuddin2017]

-   Bowel gas can limit imaging of the abdomen. Glucagon can be
    administered to reduce bowel gas motion artifact and improve the
    image.[@caridi1997; @cho2015; @criado2012; @sharafuddin2017]

#### Complications

-   Vapor lock - can occur with high volume, serial injections where
    contaminated air accumulates. Strategies to reduce incidence include
    waiting 1-3min between angiography runs. Operators should use a one
    way valve to reduce risk of air contamination.[@cho2011; @cho2015]

    -   Cardiac/pulmonary vapor lock can occur with venography. Mimics a
        PE with hypoxia and hypotension. Initial management is to place
        patient in the left lateral decubitus/trendelenberg
        position.[@caridi1997; @sharafuddin2017]

    -   Mesenteric vapor lock presents with significant unrelenting
        abdominal pain. Fluoroscopy can confirm a retained bubble.
        Initial management includes ongoing heparinization to prevent
        down stream thrombosis and maneuvers to break up the bubble by
        rotating the patient side-to-side or deep abdominal massage.
        Catheter aspiration may be needed.[@caridi1997;
        @sharafuddin2017]
