---
editor_options: 
  markdown: 
    wrap: 72
---

# Endovascular

## Radiation Safety

### Important Terms

**Absorbed Dose** - energy deposited by ionizing radiation in a medium
per unit mass. Dosage measured and communicated most commonly in Gray
(Gy) equal to 100 rad.[@reed2019]

**Effective Dose** - energy deposited by ionizing radiation in a medium,
taking into account the sensitivity of the specific tissue, time and
duration of exposure. These factors compose a weighting factor (W) and
thus this is calculated by multiplying absorbed dose (Gy) by the
weighting factor (W). Dosage measured and communicated most commonly in
Sievert (Sv) equal to 100 rem.[@reed2019]

**Reference Air Karma (RAK)** - Radiation output at a specific reference
point along a fluoroscopic axis.[@kirkwood2013]

-   Located 15cm along the beam axis toward the focal spot from the
    isocenter.

-   Best approximation of cumulative patient dose or peak skin dose
    (PSD).[@kwon2011]

-   Includes dose from fluorsocopy and fluorography acquisitions,
    however does not account for gantry angulation of changes in height.

**Substantial Radiation Dose Live (SRDL)** - defined as 5Gy exposure,
which translates to a skin dose of 3Gy and should trigger specific
patient follow up.[@baiter2011; @hirshfeld2005; @kirkwood2015;
@stecker2009]

### Radiation effects

The effects can impact both patients and clinicians. Patients often
receive a higher dose during a single procedure, where as clinician
doses, even with proper shielding, accumulate over multiple procedures
throughout their careers. The effects of radiation are defined as either
deterministic or stochastic.

|  Dose   | Effect                                                                                             |
|:----------------:|------------------------------------------------------|
|  0-2Gy  | No observable effects                                                                              |
|  2-5Gy  | Transient skin erythema and dermatitis, full recovery 6w-1yr[@guesnier-dopagne2019; @kirkwood2014] |
| 5-10Gy  | Erythema and epilation (hair loss), prolonged erythema up to 1y                                    |
| 10-15Gy | Permanent epilation, atrophy or induration up to 1y                                                |
| \>15Gy  | Dermal Necrosis                                                                                    |

: Skin related deterministic effects that can be seen after a single
exposure over a certain threshold [@balter2010; @hirshfeld2005;
@kirkwood2014; @stecker2009; @wagner1999]

The ocular lens is the most radio-sensitive tissue and cataracts is an
unfortunately common deterministic effect.[@machan2018; @brown2011]
Annual limits for ocular exposure include 20mSv per year and total
threshold of 0.5Gy.

Stochastic effects can occur after exposure of any dose, but are seen
more frequently in populations with higher radiation exposure. These are
based on population studies and exact dose dependent relationships have
not been established. These include:

-   Brain cancer[@rajaraman2016; @kirkwood2018]

-   Breast and thyroid cancer[@johnson2001; @einstein2012]

### Risk factors

Certain patient, procedure and clinician factors put patients at
increased risk for radiation exposure.[@killewich2011; @mitchell2011]
These should be considered when planing and executing endovascular
procedures to ensure that dosages are as low as reasonably achievable
(ALARA)

-   Patient Factors

    -   Obesity

-   Procedure Factors

    -   Case complexity

    -   Need for magnification

    -   Case orientation and angulation

-   Clinician Factors

    -   Use of multiple subtraction runs

### Reduction strategies

The main source of radiation to the clinicians is scatter from the
patient. There are a number of techniques that can be used to reduce
exposure of clinicians to this radiation.[@heidbuchel2014;
@kirkwood2013]

-   Reduce the time of exposure, keeping a close eye on fluoroscopy time
    and dosages as a procedure progresses.

-   Position the source as far away from the operator as possible to
    still achieve optimal imaging. Radiation dose changes according to
    the inverse square of distance. Therefore twice the distance results
    in one quarter the dose.

    -   For example, left anterior oblique (LAO) will bring the source
        to the patient's right side, causing higher doses to clinicians
        on that side of the patient.[@kirkwood2013; @sailer2019]

-   Appropriate shielding

    -   The location with the highest exposure to scatter is below the
        table.[@gonzales2014; @miller2010] Therefore, leaded skirt and
        extended lower body shields reduce radiation to the operator's
        legs.[@kirkwood2015]

    -   Of note: leaded caps DO NOT reduce radiation exposure to the
        brain because the majority of radiation is received as scatter
        from the patient up through the face and neck.[@kirkwood2018]

    -   Lead shielding should be regularly inspected and discarded if
        damaged. Particularly if defect is \>15mm2 on a critical organ
        area, \>670mm2 along a seem/overlapping area, \>11mm2 on a
        thyroid shield.[@officeofhealthcareinspections2014; @university]

-   Collimation can be helpful to reduce patient and operator dose,
    scatter and improve image quality.[@haqqani2012]

-   Use last image hold to allow for procedural planning

### Pregnancy considerations

Pregnancy of both patients and clinicians need to be considered in
relation to radiation exposure and safety.[@chandra2013; @mitchell2011;
@shaw2011] This is a highly tested subject on vascular surgery
examinations. Some important take aways include:

-   CDC has released guidance for potential prenatal effects on
    radiation exposure[@cdc2011] The majority of effects on fetuses is
    extrapolated from studies of the fall out from Hiroshima, Nagasaki
    and Chernobyl.

    -   \<0.05Gy represents no measurable risk to embryo or fetus at any
        gestational age.

    -   0.05-0.5Gy can be dangerous in the first trimester, but has not
        been associated with defects later in pregnancy.[@shaw2011]

    -   \>0.5Gy can be dangerous at any point during pregnancy.

-   Dose limit recommendations during the 9 months of pregnancy is
    500mrem or 50mrem per month.[@dauer2015; @chandra2013]

Strategies to reduce exposure include:

-   Avoid direct fluoroscopy to the fetus, high-gantry angulation, and
    femoral access

    -   Use collimation to ensure fetus is excluded from imaging field.

-   Use adjuncts of intravascular ultrasound and lead shielding when
    able.

-   Reduce machine kilo-voltage and milliampere/second.

-   Remove the anti-scatter grid to reduce dosage to patient.[@tomà2019]

-   Limit fluoro time.

-   Some recommendations state that operators who intend to get pregnant
    should start wearing maternity aprons (lead equivalent to 1mm) even
    prior to knowing they are pregnant.[@shaw2011]

    -   Original studies demonstrated reduction in fetal exposure by
        80%.[@witrak1984]

    -   However, a recent multi-institutional review showed that fetal
        exposure is minimal even in regular lead, therefore the
        additional weight of maternal lead may be
        unnecessary.[@chandra2013]

### Regulation

Joint Commission Oversight - sentinel radiation reporting is aimed to
promote awareness of preventable events perform root cause analyses to
understand the reasons for events.[@thejointcommission2019] It is
important to escalate events early, as effects may not occur until much
later.[@arbique] Sentinel events include:

1.  Cumulative dose of 15 Gy for a single field over 6mo - 1yr.

2.  Delivery of radiotherapy to the wrong body region.

3.  Actual dose more than 25% above planned radiotherapy
    dose.[@jones2011]

Institutional Oversight - many institutions develop their own guidelines
for employee exposure and mitigation strategies. Some common policies
regarding dose limits include:

-   Monthly limit for dosimeter reading of 100mrem per month.

-   Recommendations for annual occupational dose is \<20mSv per year
    averaged over 5y and no more than 50mSv in any one year.
    Occupational dose \<100mSv per year is not thought to increase
    cancer risk

    -   Recent reduction of occupational dose limit to 50mSv is due to
        increasing data connecting cataracts to radiation
        exposure.[@hamada2017]

## Contrast Reduction

The most common complications related to iodinated contrast during
endovascular procedures are hypersensitivies and acute kidney injury.
There are a number of mitigation strategies to limit the effect of
contrast on patients undergoing endovascular procedures.

In general patients with food allergies do have an increased incidence
of contrast media allergies, however no specific common allergen has
been identified. A new seafood allergy should not postpone or require
pre-medication if a patient has previously tolerated IV
contrast.[@schabelman2010]

### CO2 Angiography

CO2 angiography is often utilized in place of iodinated contrast during
fluoroscopy. A bolus of CO2 is injected, which then absorbs less
ionizing radiation than surrounding tissue and provides a map of the
arterial tree. CO2 can be used in a wide range of endovascular
procedures, even a ruptured AAA.@knipp2010 However, there are specific
limitations and complications that should be understood.

#### Limitations

-   Contraindicated in imaging above the diaphragm.[@caridi1997;
    @sharafuddin2017]

-   Susceptible to bolus fragmentation and often requires stacking to
    fully visualize the target arterial bed.[@caridi1997;
    @sharafuddin2017]

-   Bowel gas can limit imaging of the abdomen. Glucagon can be
    administered to reduce bowel gas motion artifact and improve the
    image.[@caridi1997; @cho2015; @criado2012; @sharafuddin2017]

#### Complications

-   Vapor lock - can occur with high volume, serial injections where
    contaminated air accumulates. Strategies to reduce incidence include
    waiting 1-3min between angiography runs. Operators should use a one
    way valve to reduce risk of air contamination.[@cho2011; @cho2015]

    -   Cardiac/pulmonary vapor lock can occur with venography. Mimics a
        PE with hypoxia and hypotension. Initial management is to place
        patient in the left lateral decubitus/trendelenberg
        position.[@caridi1997; @sharafuddin2017]

    -   Mesenteric vapor lock presents with significant unrelenting
        abdominal pain. Fluoroscopy can confirm a retained bubble.
        Initial management includes ongoing heparinization to prevent
        down stream thrombosis and maneuvers to break up the bubble by
        rotating the patient side-to-side or deep abdominal massage.
        Catheter aspiration may be needed.[@caridi1997;
        @sharafuddin2017]
